### ISSUE TITLE
Mentioned this plugin in QL-Wiki

### ISSUE THREAD

**Issue by rabelux** [jeremyhart/QuickLook.Plugin.HelixViewer#4]
As you are looking for feedback and I came to know your plugin only by accident I thought it would be a good idea to share this plugin on the appropriate wiki page of QuickLook (https://github.com/QL-Win/QuickLook/wiki/Available-Plugins)

I guess you are currently redesigning this plugin to fit the new way of developing plugins so feel free to delete the reference if it completely displeases you, though I made sure to mention its beta status and its different installation procedure

**Comment by jeremyhart** [comment]
Thanks @rabelux, I've updated that page for the latest release
